config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    collection do
      post:confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates:content,presence:true
    validates:content,length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action:set_tweet,only:[:show,:edit,:update,:destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path,notice:"Tweetが投稿されました。"
    else
      render'new'
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path,notice:"Tweetを編集しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path,notice:"Tweetを削除しました。"
  end

  def confirm 
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title,:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' ||action_name =='confirm'
      onfirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head> 
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Tsubuyaki</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="../../assets/stylesheets/tweets.scss"> -->
    <!-- <link rel="stylesheet" href="vendors/css/.css"> -->
  </head>

  <body>
    <header class="header">
    <nav>
      <div class="left clearfix">
       <h1>Tsubuyaki(header)</h1>
      </div>
    </nav>
  </header>
  <%= yield %>
    
    <footer class="footer">
     <p>Tsubuyaki株式会社 <br>
      © 2015-2018 Copyright Tsubuyaki Corp.</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true ,url:choose_new_or_edit ) do |form| %>




  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="tweet_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @tweet.content %></p>
  <%= form.submit  "投稿する" %>
<% end %>


<%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る" ,name: 'back' %>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>tweet投稿一覧</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= link_to '詳細', tweet_path(tweet.id) %></td>
        <td><%= link_to '編集', edit_tweet_path(tweet.id) %></td>
        <td><%= link_to '削除', tweet_path(tweet.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h1>tweet詳細画面</h1>

<p>内容：<%= @tweet.content %></p>